#!/bin/sh

# Copyright (c) 2015, Rice University
# All rights reserved.
#
# Author(s): Neil T. Dantam <ntd@rice.edu>
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#   * Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#  COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
#  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
#  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
#  OF THE POSSIBILITY OF SUCH DAMAGE.

OUTPUT_FILE=aarxc.out.c
SCENE_NAME=""
MESH_UP_AXIS="Z"
MESH_FORWARD_AXIS="Y"
RELOAD="nil"


AARX_MEMORY_DEFAULT="2GB"

if [ -n "$AARX_RELOAD" ]; then
    RELOAD=t
fi

while test "$1" != x-- -a "x$#" != x0; do
    case "$1" in
        -h|-\?|--help)
            cat <<EOF
Usage: aarxc [OPTION] scene-files...
Generate C code from scene graph files files

Options:
  -h|-?|--help,                  display this help and exit
  -o OUTPUT-FILE                 write generated code to OUTPUT_FILE
  -n SCENE_NAME                  name of the scene graph
  -U UP_AXIS                     up axis of mesh files
  -F FORWARD_AXIS                forward axis of mesh files
  -R                             reload files
  -g,--gui                       Display scene in a GUI

Environment:

  ROS_PACKAGE_PATH               Location of ROS packages, necessary to load URDF

  AARX_MEMORY                    Maximum heap memory size ($AARX_MEMORY_DEFAULT)

  AARX_TMPDIR                    Directory for temporary and cache files (/tmp/amino-USERNAME)

Files:

  /tmp/amino-USERNAME            Default directory for temporary and cache files, set via \$AARX_TMPDIR

Examples:

  aarxc robot.urdf -o robot.c     Generate robot.c from URDF file robot.urdf

  aarxc --gui robot.urdf          Render robot.urdf in the OpenGL viewer

Report bugs to <ntd@rice.edu>"
EOF
            exit 0
            ;;
        -o)
            shift
            export AARX_OUTPUT="$1";
            ;;
        -n)
            shift
            export AARX_SCENE_NAME="$1";
            ;;
        -U)
            shift
            export AARX_MESH_UP_AXIS="$1";
            ;;
        -F)
            shift
            export AARX_MESH_FORWARD_AXIS="$1";
            ;;
        -R)
            export AARX_RELOAD=t
            ;;
        --gui|-g)
            export AARX_GUI=t
            ;;
        --version)
            export AARX_VERSION="1"
            ;;
        --version-man)
            export AARX_VERSION_MAN="1"
            ;;
        -*)
            echo "error: unknown option: $1"
            exit 1
            ;;
        *)
            export AARX_SCENE="$AARX_SCENE \"$1\""
            ;;
    esac
    shift
done

if test -z "$AARX_MEMORY"; then
    AARX_MEMORY="$AARX_MEMORY_DEFAULT"
fi




exec aarx.core --dynamic-space-size "$AARX_MEMORY" \
     --non-interactive \
     --no-userinit \
     --eval '(robray::aarx-command)'
